services:
  api:
    image: lionel38190/jarvisapi:${VERSION_TAG:-latest}
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HUE_BRIDGE_IP=${HUE_BRIDGE_IP:-localhost}
      - HUE_USER=${HUE_USER:-empty}

  web:
    image: lionel38190/jarvisweb:${VERSION_TAG:-latest}
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_HOST=api
    depends_on:
      - api
